apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
 # alerting:
 #   alertmanagers:
  #  - name: alertmanager-main
  #    namespace: monitoring
  #    port: web
  image: quay.io/prometheus/prometheus:v2.20.0
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
#  remoteRead: 
#  - url: http://10.169.170.43:8481/select/0/prometheus
  remoteWrite:
 # - writeRelabelConfigs:
#    - sourceLabels: ['prometheus_replica']
 #     action: 'drop'
  - url: http://10.167.169.92:19000/prometheus/v1/write
  resources:
    requests:
      memory: 400Mi
 # ruleSelector:
 #   matchLabels:
 #     prometheus: k8s
 #     role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.20.0
#  storage:
#    volumeClaimTemplate:
#      spec:
#        storageClassName: dynamic-ceph-rbd
#        resources:
#          requests:
#            storage: 5Gi
